### ISSUE TITLE
無法開啟影片

### ISSUE THREAD

**Issue by JulianLai** [YWJamesLin/bahamut_anime_player_kodi#1]
已安裝 python-requests、python-bs4、python-pickleshare、python-uritools、python-ipaddress
Kodi 版本：17.0 beta6

以下是他的 log：

> 16:00:49.646 T:139831032141568   ERROR: Previous line repeats 6 times.
> 16:00:49.646 T:139831032141568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'requests.exceptions.MissingSchema'>
>                                             Error Contents: Invalid URL 'https:': No schema supplied. Perhaps you meant http://https:?
>                                             Traceback (most recent call last):
>                                               File "/home/user/.kodi/addons/plugin.video.anigamer/addon.py", line 254, in <module>
>                                                 router (sys.argv[2], action)
>                                               File "/home/user/.kodi/addons/plugin.video.anigamer/addon.py", line 247, in router
>                                                 action.play (params['sn'])
>                                               File "/home/user/.kodi/addons/plugin.video.anigamer/addon.py", line 228, in play
>                                                 result = self.sessionAgent.get (src)
>                                               File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
>                                                 return self.request('GET', url, **kwargs)
>                                               File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 454, in request
>                                                 prep = self.prepare_request(req)
>                                               File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 388, in prepare_request
>                                                 hooks=merge_hooks(request.hooks, self.hooks),
>                                               File "/usr/lib/python2.7/dist-packages/requests/models.py", line 293, in prepare
>                                                 self.prepare_url(url, params)
>                                               File "/usr/lib/python2.7/dist-packages/requests/models.py", line 353, in prepare_url
>                                                 raise MissingSchema(error)
>                                             MissingSchema: Invalid URL 'https:': No schema supplied. Perhaps you meant http://https:?
>                                             -->End of Python script error report<--
> 16:00:49.674 T:139831040534272  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
> 16:00:51.683 T:139831032141568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'requests.exceptions.MissingSchema'>
>                                             Error Contents: Invalid URL 'https:': No schema supplied. Perhaps you meant http://https:?
>                                             Traceback (most recent call last):
>                                               File "/home/user/.kodi/addons/plugin.video.anigamer/addon.py", line 254, in <module>
>                                                 router (sys.argv[2], action)
>                                               File "/home/user/.kodi/addons/plugin.video.anigamer/addon.py", line 247, in router
>                                                 action.play (params['sn'])
>                                               File "/home/user/.kodi/addons/plugin.video.anigamer/addon.py", line 228, in play
>                                                 result = self.sessionAgent.get (src)
>                                               File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
>                                                 return self.request('GET', url, **kwargs)
>                                               File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 454, in request
>                                                 prep = self.prepare_request(req)
>                                               File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 388, in prepare_request
>                                                 hooks=merge_hooks(request.hooks, self.hooks),
>                                               File "/usr/lib/python2.7/dist-packages/requests/models.py", line 293, in prepare
>                                                 self.prepare_url(url, params)
>                                               File "/usr/lib/python2.7/dist-packages/requests/models.py", line 353, in prepare_url
>                                                 raise MissingSchema(error)
>                                             MissingSchema: Invalid URL 'https:': No schema supplied. Perhaps you meant http://https:?
>                                             -->End of Python script error report<--

**Comment by YWJamesLin** [comment]
I understand what happened, so I'm going to fix it now.

2016/12/04 16:21
@JulianLai This new commit of the master branch may fix this issue.
